In [9]:
import tensorflow as tf
import numpy as np

In [3]:
#Tensor 0-chiều
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
r1 = tf.constant(9, tf.int16)
print(r1)
r1_float = tf.constant(1.12, tf.float32)
print(r1_float)
r1_string = tf.constant("Hello VanLang University", tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello VanLang University', shape=(), dtype=string)


In [4]:
#Tensor 1-chiều
rank_1_tensor = tf.constant = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [22]:
import tensorflow as tf

# Tensor 2-chiều(ma trận)
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)

print(rank_2_tensor)

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object is not callable

In [25]:
# Tensor n-chiều(nhiều trục)
import tensorflow as tf
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
      [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
      [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
      [25, 26, 27, 28, 29]],
])

print(rank_3_tensor)
print('shape:', rank_3_tensor.shape)
print('type of tensor:', rank_3_tensor.dtype)

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object is not callable

In [28]:
t_zero = tf.zeros([10])
print(t_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


In [29]:
t_2_zero = tf.zeros([3, 3])
print(t_2_zero)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [30]:
t_3_zero = tf.zeros([3, 3, 5])
print(t_3_zero)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


In [31]:
t_one = tf.ones([10])
print(t_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)


In [32]:
t_2_one =tf.ones([3, 3])
print(t_2_one)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [33]:
t_3_one =tf.ones([3, 3, 5])
print(t_3_one)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


In [34]:
t_1 = tf.fill(3, 10)
print(t_1)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [35]:
t_2 = tf.fill([3, 3], 9)
print(t_2)

tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


In [36]:
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


In [37]:
range_tensor = tf.range(3.0, 7.0, delta =0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)


In [38]:
range_tensor = tf.range(3.0, delta = 0.5)
print(range_tensor)

tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


In [39]:
range_tensor = tf.random.normal([5])
print(range_tensor)

tf.Tensor([ 0.23445092 -0.19531867  0.50689423  2.1191952   1.2022612 ], shape=(5,), dtype=float32)


In [40]:
range_tensor = tf.random.uniform([3, 3])
print(range_tensor)

tf.Tensor(
[[0.3295095  0.32652855 0.0810411 ]
 [0.4569955  0.64170516 0.00730848]
 [0.1123724  0.51106787 0.99905133]], shape=(3, 3), dtype=float32)


In [41]:
range_tensor = tf.random.normal([5])
print(range_tensor)

tf.Tensor([-1.0314088   0.2145893  -1.7714021  -0.24859113 -0.522188  ], shape=(5,), dtype=float32)


In [42]:
range_tensor = tf.random.truncated_normal([3, 2])
print(range_tensor)

tf.Tensor(
[[-0.18493575 -0.08260385]
 [-0.34577477 -0.12870641]
 [ 0.3522634   0.5213144 ]], shape=(3, 2), dtype=float32)


In [44]:
range_tensor = tf.random.truncated_normal([3, 2, 2])
print(range_tensor)

tf.Tensor(
[[[-0.49795786  1.3827486 ]
  [ 0.12775727 -0.6814484 ]]

 [[-0.07446695  0.32606333]
  [-0.7723279   1.0772994 ]]

 [[ 1.5246104  -0.22155711]
  [-0.19490525  0.42935178]]], shape=(3, 2, 2), dtype=float32)


In [45]:
range_tensor = tf.random.uniform([5], minval =10, maxval = 20)
print(range_tensor)

tf.Tensor([13.037046 10.424167 19.368553 11.412266 11.537709], shape=(5,), dtype=float32)


In [47]:
range_tensor = tf.random.uniform([3, 2], minval = 10, maxval =20)
print(range_tensor)

tf.Tensor(
[[12.574063 12.353097]
 [10.292744 10.320331]
 [11.968141 18.560188]], shape=(3, 2), dtype=float32)


In [46]:
range_tensor = tf.random.uniform([3, 2, 5], minval = 10, maxval =20)
print(range_tensor)

tf.Tensor(
[[[16.389236  11.061564  16.170145  11.410198  14.508218 ]
  [19.517471  14.506224  12.196445  15.287668  15.9654255]]

 [[18.400402  10.655684  17.91586   13.066528  16.461176 ]
  [18.474953  17.680363  14.994832  10.250036  17.303024 ]]

 [[19.67274   19.592218  15.214443  15.315983  17.727827 ]
  [10.800751  10.489264  19.804348  13.281932  18.345774 ]]], shape=(3, 2, 5), dtype=float32)


In [48]:
range_tensor = tf.random.uniform([5], minval = 10, maxval = 20)
print(range_tensor)
print(tf.random.shuffle(range_tensor))

tf.Tensor([12.425107  14.1325035 11.240215  17.602703  11.063034 ], shape=(5,), dtype=float32)
tf.Tensor([11.063034  17.602703  14.1325035 11.240215  12.425107 ], shape=(5,), dtype=float32)


In [49]:
t_float = tf.constant(3.9, tf.float32)
print(t_float,'---', t_float.dtype)
t_int = tf.cast(t_float, tf.int32)
print(t_int,'---', t_int.dtype)

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object is not callable